### ISSUE TITLE
Redirecting with `302 Found` rolls back transaction.

### ISSUE THREAD

**Issue by lyssieth** [Defelo/poem-ext#13]
The situation is this:
- I have a login screen, which POSTs to `/login`
- `/login`, if the information is valid, sets a cookie based on a value created in the database, then then does a `302 Found` redirect to `/dashboard`

The value created in the database, however, is rolled back, thus making the cookie's contents invalid, and making `/dashboard` error out (by redirecting to `/login` with a message stating that the session token was invalid).

Is there a way to avoid the rollback?
Or, maybe supporting a custom success check function in `DbTransactionMiddleware` might be a better idea?
Something equivalent to a `fn(&Response) -> bool`?

**Comment by Defelo** [comment]
Ah, I haven't thought about redirect status codes when implementing this feature. But sure, we should only rollback the transaction if an error actually occured. Would you like to submit a pull request to change this behavior (and perhaps add a function to provide a custom success check function to the middleware)?

**Comment by lyssieth** [comment]
Sure, I'll try and throw something together.

**Comment by lyssieth** [comment]
I opened #14.
